-- Forge — 0007_seed_sde_questions.sql
-- Seeds the 190-question Striver SDE Sheet as a CHECKLIST challenge for the
-- CURRENTLY AUTHENTICATED user. Run this while signed in (so auth.uid() resolves).
-- Idempotent: find-or-create the challenge by name, and insert only items whose
-- sort_order is not already present. Safe to re-run. Requires 0006.
-- Generated from striver_sde_sheet.json (190 rows, 27 sections).

do $$
declare
  uid     uuid := auth.uid();
  chal_id uuid;
begin
  if uid is null then
    raise exception 'No auth.uid(): run this migration while authenticated.';
  end if;

  select id into chal_id from challenges
    where user_id = uid and kind = 'checklist' and name = 'Striver SDE Sheet (190)'
    limit 1;

  if chal_id is null then
    insert into challenges (user_id, name, description, status, kind, is_public)
    values (
      uid,
      'Striver SDE Sheet (190)',
      'The 190-question Striver SDE Sheet. Check off questions as you solve them — the bar fills by completion.',
      'Active',
      'checklist',
      false
    )
    returning id into chal_id;
  end if;

  insert into challenge_items
    (user_id, challenge_id, section, sort_order, title, difficulty, url, source, external_ref)
  select uid, chal_id, v.section, v.sort_order, v.title,
         v.difficulty::difficulty_level, v.url, v.source, v.external_ref
  from (values
    (1, 'Arrays', 'Set Matrix Zeroes', 'Medium', 'https://leetcode.com/problems/set-matrix-zeroes/', 'leetcode', 'set-matrix-zeroes'),
    (2, 'Arrays', 'Pascal''s Triangle', 'Easy', 'https://leetcode.com/problems/pascals-triangle/', 'leetcode', 'pascals-triangle'),
    (3, 'Arrays', 'Next Permutation', 'Medium', 'https://leetcode.com/problems/next-permutation/', 'leetcode', 'next-permutation'),
    (4, 'Arrays', 'Maximum Subarray (Kadane''s Algorithm)', 'Medium', 'https://leetcode.com/problems/maximum-subarray/', 'leetcode', 'maximum-subarray'),
    (5, 'Arrays', 'Sort Colors (Sort an array of 0s, 1s, and 2s)', 'Medium', 'https://leetcode.com/problems/sort-colors/', 'leetcode', 'sort-colors'),
    (6, 'Arrays', 'Best Time to Buy and Sell Stock', 'Easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 'leetcode', 'best-time-to-buy-and-sell-stock'),
    (7, 'Arrays Part-II', 'Rotate Image', 'Medium', 'https://leetcode.com/problems/rotate-image/', 'leetcode', 'rotate-image'),
    (8, 'Arrays Part-II', 'Merge Intervals', 'Medium', 'https://leetcode.com/problems/merge-intervals/', 'leetcode', 'merge-intervals'),
    (9, 'Arrays Part-II', 'Merge Sorted Array', 'Easy', 'https://leetcode.com/problems/merge-sorted-array/', 'leetcode', 'merge-sorted-array'),
    (10, 'Arrays Part-II', 'Find the Duplicate Number', 'Medium', 'https://leetcode.com/problems/find-the-duplicate-number/', 'leetcode', 'find-the-duplicate-number'),
    (11, 'Arrays Part-II', 'Repeat and Missing Number Array', 'Medium', 'https://www.interviewbit.com/problems/repeat-and-missing-number-array/', 'interviewbit', null),
    (12, 'Arrays Part-II', 'Count Inversions', 'Hard', 'https://practice.geeksforgeeks.org/problems/inversion-of-array-1587115620/1', 'geeksforgeeks', null),
    (13, 'Arrays Part-III', 'Search a 2D Matrix', 'Medium', 'https://leetcode.com/problems/search-a-2d-matrix/', 'leetcode', 'search-a-2d-matrix'),
    (14, 'Arrays Part-III', 'Pow(x, n)', 'Medium', 'https://leetcode.com/problems/powx-n/', 'leetcode', 'powx-n'),
    (15, 'Arrays Part-III', 'Majority Element (>N/2 times)', 'Easy', 'https://leetcode.com/problems/majority-element/', 'leetcode', 'majority-element'),
    (16, 'Arrays Part-III', 'Majority Element II (>N/3 times)', 'Medium', 'https://leetcode.com/problems/majority-element-ii/', 'leetcode', 'majority-element-ii'),
    (17, 'Arrays Part-III', 'Unique Paths', 'Medium', 'https://leetcode.com/problems/unique-paths/', 'leetcode', 'unique-paths'),
    (18, 'Arrays Part-III', 'Reverse Pairs', 'Hard', 'https://leetcode.com/problems/reverse-pairs/', 'leetcode', 'reverse-pairs'),
    (19, 'Arrays Part-IV', 'Two Sum', 'Easy', 'https://leetcode.com/problems/two-sum/', 'leetcode', 'two-sum'),
    (20, 'Arrays Part-IV', '4Sum', 'Medium', 'https://leetcode.com/problems/4sum/', 'leetcode', '4sum'),
    (21, 'Arrays Part-IV', 'Longest Consecutive Sequence', 'Medium', 'https://leetcode.com/problems/longest-consecutive-sequence/', 'leetcode', 'longest-consecutive-sequence'),
    (22, 'Arrays Part-IV', 'Largest subarray with 0 sum', 'Medium', 'https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1', 'geeksforgeeks', null),
    (23, 'Arrays Part-IV', 'Subarray with given XOR', 'Medium', 'https://www.interviewbit.com/problems/subarray-with-given-xor/', 'interviewbit', null),
    (24, 'Arrays Part-IV', 'Longest Substring Without Repeating Characters', 'Medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 'leetcode', 'longest-substring-without-repeating-characters'),
    (25, 'Linked List', 'Reverse Linked List', 'Easy', 'https://leetcode.com/problems/reverse-linked-list/', 'leetcode', 'reverse-linked-list'),
    (26, 'Linked List', 'Middle of the Linked List', 'Easy', 'https://leetcode.com/problems/middle-of-the-linked-list/', 'leetcode', 'middle-of-the-linked-list'),
    (27, 'Linked List', 'Merge Two Sorted Lists', 'Easy', 'https://leetcode.com/problems/merge-two-sorted-lists/', 'leetcode', 'merge-two-sorted-lists'),
    (28, 'Linked List', 'Remove Nth Node From End of List', 'Medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 'leetcode', 'remove-nth-node-from-end-of-list'),
    (29, 'Linked List', 'Add Two Numbers', 'Medium', 'https://leetcode.com/problems/add-two-numbers/', 'leetcode', 'add-two-numbers'),
    (30, 'Linked List', 'Delete Node in a Linked List', 'Medium', 'https://leetcode.com/problems/delete-node-in-a-linked-list/', 'leetcode', 'delete-node-in-a-linked-list'),
    (31, 'Linked List Part-II', 'Intersection of Two Linked Lists', 'Easy', 'https://leetcode.com/problems/intersection-of-two-linked-lists/', 'leetcode', 'intersection-of-two-linked-lists'),
    (32, 'Linked List Part-II', 'Linked List Cycle', 'Easy', 'https://leetcode.com/problems/linked-list-cycle/', 'leetcode', 'linked-list-cycle'),
    (33, 'Linked List Part-II', 'Reverse Nodes in k-Group', 'Hard', 'https://leetcode.com/problems/reverse-nodes-in-k-group/', 'leetcode', 'reverse-nodes-in-k-group'),
    (34, 'Linked List Part-II', 'Palindrome Linked List', 'Easy', 'https://leetcode.com/problems/palindrome-linked-list/', 'leetcode', 'palindrome-linked-list'),
    (35, 'Linked List Part-II', 'Linked List Cycle II', 'Medium', 'https://leetcode.com/problems/linked-list-cycle-ii/', 'leetcode', 'linked-list-cycle-ii'),
    (36, 'Linked List Part-II', 'Flattening a Linked List', 'Medium', 'https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1', 'geeksforgeeks', null),
    (37, 'Linked List and Arrays', 'Rotate List', 'Medium', 'https://leetcode.com/problems/rotate-list/', 'leetcode', 'rotate-list'),
    (38, 'Linked List and Arrays', 'Copy List with Random Pointer', 'Medium', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 'leetcode', 'copy-list-with-random-pointer'),
    (39, 'Linked List and Arrays', '3Sum', 'Medium', 'https://leetcode.com/problems/3sum/', 'leetcode', '3sum'),
    (40, 'Linked List and Arrays', 'Trapping Rain Water', 'Hard', 'https://leetcode.com/problems/trapping-rain-water/', 'leetcode', 'trapping-rain-water'),
    (41, 'Linked List and Arrays', 'Remove Duplicates from Sorted Array', 'Easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', 'leetcode', 'remove-duplicates-from-sorted-array'),
    (42, 'Linked List and Arrays', 'Max Consecutive Ones', 'Easy', 'https://leetcode.com/problems/max-consecutive-ones/', 'leetcode', 'max-consecutive-ones'),
    (43, 'Greedy Algorithm', 'N meetings in one room', 'Medium', 'https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1', 'geeksforgeeks', null),
    (44, 'Greedy Algorithm', 'Minimum Platforms', 'Medium', 'https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1', 'geeksforgeeks', null),
    (45, 'Greedy Algorithm', 'Job Sequencing Problem', 'Medium', 'https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1', 'geeksforgeeks', null),
    (46, 'Greedy Algorithm', 'Fractional Knapsack', 'Medium', 'https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1', 'geeksforgeeks', null),
    (47, 'Greedy Algorithm', 'Find Minimum Number of Coins', 'Medium', 'https://practice.geeksforgeeks.org/problems/number-of-coins1824/1', 'geeksforgeeks', null),
    (48, 'Greedy Algorithm', 'Assign Mice to Holes', 'Easy', 'https://www.interviewbit.com/problems/assign-mice-to-holes/', 'interviewbit', null),
    (49, 'Recursion', 'Subset Sums', 'Easy', 'https://practice.geeksforgeeks.org/problems/subset-sums2234/1', 'geeksforgeeks', null),
    (50, 'Recursion', 'Subsets II', 'Medium', 'https://leetcode.com/problems/subsets-ii/', 'leetcode', 'subsets-ii'),
    (51, 'Recursion', 'Combination Sum', 'Medium', 'https://leetcode.com/problems/combination-sum/', 'leetcode', 'combination-sum'),
    (52, 'Recursion', 'Combination Sum II', 'Medium', 'https://leetcode.com/problems/combination-sum-ii/', 'leetcode', 'combination-sum-ii'),
    (53, 'Recursion', 'Palindrome Partitioning', 'Medium', 'https://leetcode.com/problems/palindrome-partitioning/', 'leetcode', 'palindrome-partitioning'),
    (54, 'Recursion', 'Permutation Sequence', 'Hard', 'https://leetcode.com/problems/permutation-sequence/', 'leetcode', 'permutation-sequence'),
    (55, 'Recursion and Backtracking', 'Permutations', 'Medium', 'https://leetcode.com/problems/permutations/', 'leetcode', 'permutations'),
    (56, 'Recursion and Backtracking', 'N-Queens', 'Hard', 'https://leetcode.com/problems/n-queens/', 'leetcode', 'n-queens'),
    (57, 'Recursion and Backtracking', 'Sudoku Solver', 'Hard', 'https://leetcode.com/problems/sudoku-solver/', 'leetcode', 'sudoku-solver'),
    (58, 'Recursion and Backtracking', 'M-Coloring Problem', 'Medium', 'https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1', 'geeksforgeeks', null),
    (59, 'Recursion and Backtracking', 'Rat in a Maze Problem - I', 'Medium', 'https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1', 'geeksforgeeks', null),
    (60, 'Recursion and Backtracking', 'Word Break II', 'Hard', 'https://leetcode.com/problems/word-break-ii/', 'leetcode', 'word-break-ii'),
    (61, 'Binary Search', 'The N-th root of an integer', 'Easy', 'https://practice.geeksforgeeks.org/problems/find-nth-root-of-m5843/1', 'geeksforgeeks', null),
    (62, 'Binary Search', 'Matrix Median', 'Medium', 'https://www.interviewbit.com/problems/matrix-median/', 'interviewbit', null),
    (63, 'Binary Search', 'Single Element in a Sorted Array', 'Medium', 'https://leetcode.com/problems/single-element-in-a-sorted-array/', 'leetcode', 'single-element-in-a-sorted-array'),
    (64, 'Binary Search', 'Search in Rotated Sorted Array', 'Medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 'leetcode', 'search-in-rotated-sorted-array'),
    (65, 'Binary Search', 'Median of Two Sorted Arrays', 'Hard', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', 'leetcode', 'median-of-two-sorted-arrays'),
    (66, 'Binary Search', 'K-th element of two sorted Arrays', 'Medium', 'https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1', 'geeksforgeeks', null),
    (67, 'Binary Search', 'Allocate Books', 'Hard', 'https://www.interviewbit.com/problems/allocate-books/', 'interviewbit', null),
    (68, 'Binary Search', 'Aggressive Cows', 'Hard', 'https://practice.geeksforgeeks.org/problems/aggressive-cows/1', 'geeksforgeeks', null),
    (69, 'Heaps', 'Max heap, Min Heap Implementation', 'Medium', 'https://practice.geeksforgeeks.org/problems/operations-on-binary-min-heap/1', 'geeksforgeeks', null),
    (70, 'Heaps', 'Kth Largest Element in an Array', 'Medium', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'leetcode', 'kth-largest-element-in-an-array'),
    (71, 'Heaps', 'Maximum Sum Combination', 'Medium', 'https://www.interviewbit.com/problems/maximum-sum-combinations/', 'interviewbit', null),
    (72, 'Heaps', 'Find Median from Data Stream', 'Hard', 'https://leetcode.com/problems/find-median-from-data-stream/', 'leetcode', 'find-median-from-data-stream'),
    (73, 'Heaps', 'Merge k Sorted Arrays', 'Medium', 'https://practice.geeksforgeeks.org/problems/merge-k-sorted-arrays/1', 'geeksforgeeks', null),
    (74, 'Heaps', 'Top K Frequent Elements', 'Medium', 'https://leetcode.com/problems/top-k-frequent-elements/', 'leetcode', 'top-k-frequent-elements'),
    (75, 'Stack and Queue', 'Implement Stack using Arrays', 'Easy', 'https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1', 'geeksforgeeks', null),
    (76, 'Stack and Queue', 'Implement Queue using Arrays', 'Easy', 'https://practice.geeksforgeeks.org/problems/implement-queue-using-array/1', 'geeksforgeeks', null),
    (77, 'Stack and Queue', 'Implement Stack using Queues', 'Easy', 'https://leetcode.com/problems/implement-stack-using-queues/', 'leetcode', 'implement-stack-using-queues'),
    (78, 'Stack and Queue', 'Implement Queue using Stacks', 'Easy', 'https://leetcode.com/problems/implement-queue-using-stacks/', 'leetcode', 'implement-queue-using-stacks'),
    (79, 'Stack and Queue', 'Valid Parentheses', 'Easy', 'https://leetcode.com/problems/valid-parentheses/', 'leetcode', 'valid-parentheses'),
    (80, 'Stack and Queue', 'Next Greater Element I', 'Easy', 'https://leetcode.com/problems/next-greater-element-i/', 'leetcode', 'next-greater-element-i'),
    (81, 'Stack and Queue', 'Sort a Stack', 'Medium', 'https://practice.geeksforgeeks.org/problems/sort-a-stack/1', 'geeksforgeeks', null),
    (82, 'Stack and Queue Part-II', 'Next Smaller Element', 'Medium', 'https://www.interviewbit.com/problems/nearest-smaller-element/', 'interviewbit', null),
    (83, 'Stack and Queue Part-II', 'LRU Cache', 'Medium', 'https://leetcode.com/problems/lru-cache/', 'leetcode', 'lru-cache'),
    (84, 'Stack and Queue Part-II', 'LFU Cache', 'Hard', 'https://leetcode.com/problems/lfu-cache/', 'leetcode', 'lfu-cache'),
    (85, 'Stack and Queue Part-II', 'Largest Rectangle in Histogram', 'Hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', 'leetcode', 'largest-rectangle-in-histogram'),
    (86, 'Stack and Queue Part-II', 'Sliding Window Maximum', 'Hard', 'https://leetcode.com/problems/sliding-window-maximum/', 'leetcode', 'sliding-window-maximum'),
    (87, 'Stack and Queue Part-II', 'Min Stack', 'Medium', 'https://leetcode.com/problems/min-stack/', 'leetcode', 'min-stack'),
    (88, 'Stack and Queue Part-II', 'Rotting Oranges', 'Medium', 'https://leetcode.com/problems/rotting-oranges/', 'leetcode', 'rotting-oranges'),
    (89, 'Stack and Queue Part-II', 'Online Stock Span', 'Medium', 'https://leetcode.com/problems/online-stock-span/', 'leetcode', 'online-stock-span'),
    (90, 'Stack and Queue Part-II', 'Maximum of minimum for every window size', 'Hard', 'https://practice.geeksforgeeks.org/problems/maximum-of-minimum-for-every-window-size3453/1', 'geeksforgeeks', null),
    (91, 'Stack and Queue Part-II', 'The Celebrity Problem', 'Medium', 'https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1', 'geeksforgeeks', null),
    (92, 'String', 'Reverse Words in a String', 'Medium', 'https://leetcode.com/problems/reverse-words-in-a-string/', 'leetcode', 'reverse-words-in-a-string'),
    (93, 'String', 'Longest Palindromic Substring', 'Medium', 'https://leetcode.com/problems/longest-palindromic-substring/', 'leetcode', 'longest-palindromic-substring'),
    (94, 'String', 'Roman to Integer', 'Easy', 'https://leetcode.com/problems/roman-to-integer/', 'leetcode', 'roman-to-integer'),
    (95, 'String', 'String to Integer (atoi)', 'Medium', 'https://leetcode.com/problems/string-to-integer-atoi/', 'leetcode', 'string-to-integer-atoi'),
    (96, 'String', 'Longest Common Prefix', 'Easy', 'https://leetcode.com/problems/longest-common-prefix/', 'leetcode', 'longest-common-prefix'),
    (97, 'String', 'Rabin-Karp Algorithm for Pattern Searching', 'Medium', 'https://practice.geeksforgeeks.org/problems/31272eef104840f7430ad9fd1d43b434a4cea159/1', 'geeksforgeeks', null),
    (98, 'String Part-II', 'Find the Index of the First Occurrence in a String (Z-Function)', 'Medium', 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', 'leetcode', 'find-the-index-of-the-first-occurrence-in-a-string'),
    (99, 'String Part-II', 'KMP Algorithm', 'Medium', 'https://practice.geeksforgeeks.org/problems/search-pattern-kmp-algorithm/1', 'geeksforgeeks', null),
    (100, 'String Part-II', 'Minimum Insertion Steps to Make a String Palindrome', 'Hard', 'https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/', 'leetcode', 'minimum-insertion-steps-to-make-a-string-palindrome'),
    (101, 'String Part-II', 'Valid Anagram', 'Easy', 'https://leetcode.com/problems/valid-anagram/', 'leetcode', 'valid-anagram'),
    (102, 'String Part-II', 'Count and Say', 'Medium', 'https://leetcode.com/problems/count-and-say/', 'leetcode', 'count-and-say'),
    (103, 'String Part-II', 'Compare Version Numbers', 'Medium', 'https://leetcode.com/problems/compare-version-numbers/', 'leetcode', 'compare-version-numbers'),
    (104, 'Binary Tree', 'Inorder Traversal', 'Easy', 'https://leetcode.com/problems/binary-tree-inorder-traversal/', 'leetcode', 'binary-tree-inorder-traversal'),
    (105, 'Binary Tree', 'Preorder Traversal', 'Easy', 'https://leetcode.com/problems/binary-tree-preorder-traversal/', 'leetcode', 'binary-tree-preorder-traversal'),
    (106, 'Binary Tree', 'Postorder Traversal', 'Easy', 'https://leetcode.com/problems/binary-tree-postorder-traversal/', 'leetcode', 'binary-tree-postorder-traversal'),
    (107, 'Binary Tree', 'Morris Inorder Traversal', 'Hard', 'https://leetcode.com/problems/binary-tree-inorder-traversal/', 'leetcode', 'binary-tree-inorder-traversal'),
    (108, 'Binary Tree', 'Morris Preorder Traversal', 'Hard', 'https://leetcode.com/problems/binary-tree-preorder-traversal/', 'leetcode', 'binary-tree-preorder-traversal'),
    (109, 'Binary Tree', 'LeftView Of Binary Tree', 'Easy', 'https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1', 'geeksforgeeks', null),
    (110, 'Binary Tree', 'Bottom View of Binary Tree', 'Medium', 'https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1', 'geeksforgeeks', null),
    (111, 'Binary Tree', 'Top View of Binary Tree', 'Medium', 'https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1', 'geeksforgeeks', null),
    (112, 'Binary Tree', 'Preorder Inorder Postorder in a single traversal', 'Medium', 'https://www.codingninjas.com/studio/problems/981269', 'codingninjas', null),
    (113, 'Binary Tree', 'Vertical Order Traversal', 'Hard', 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/', 'leetcode', 'vertical-order-traversal-of-a-binary-tree'),
    (114, 'Binary Tree', 'Root to Node Path in Binary Tree', 'Easy', 'https://www.interviewbit.com/problems/path-to-given-node/', 'interviewbit', null),
    (115, 'Binary Tree', 'Max width of a Binary Tree', 'Medium', 'https://leetcode.com/problems/maximum-width-of-binary-tree/', 'leetcode', 'maximum-width-of-binary-tree'),
    (116, 'Binary Tree part-II', 'Level order Traversal / Level order traversal in spiral form', 'Medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 'leetcode', 'binary-tree-level-order-traversal'),
    (117, 'Binary Tree part-II', 'Height of a Binary Tree', 'Easy', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 'leetcode', 'maximum-depth-of-binary-tree'),
    (118, 'Binary Tree part-II', 'Diameter of Binary Tree', 'Easy', 'https://leetcode.com/problems/diameter-of-binary-tree/', 'leetcode', 'diameter-of-binary-tree'),
    (119, 'Binary Tree part-II', 'Check if the Binary tree is height-balanced or not', 'Easy', 'https://leetcode.com/problems/balanced-binary-tree/', 'leetcode', 'balanced-binary-tree'),
    (120, 'Binary Tree part-II', 'LCA in Binary Tree', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', 'leetcode', 'lowest-common-ancestor-of-a-binary-tree'),
    (121, 'Binary Tree part-II', 'Check if two trees are identical or not', 'Easy', 'https://leetcode.com/problems/same-tree/', 'leetcode', 'same-tree'),
    (122, 'Binary Tree part-II', 'Zig Zag Traversal of Binary Tree', 'Medium', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', 'leetcode', 'binary-tree-zigzag-level-order-traversal'),
    (123, 'Binary Tree part-II', 'Boundary Traversal of Binary Tree', 'Medium', 'https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1', 'geeksforgeeks', null),
    (124, 'Binary Tree part-III', 'Maximum path sum', 'Hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 'leetcode', 'binary-tree-maximum-path-sum'),
    (125, 'Binary Tree part-III', 'Construct Binary Tree from inorder and preorder', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 'leetcode', 'construct-binary-tree-from-preorder-and-inorder-traversal'),
    (126, 'Binary Tree part-III', 'Construct Binary Tree from Inorder and Postorder', 'Medium', 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/', 'leetcode', 'construct-binary-tree-from-inorder-and-postorder-traversal'),
    (127, 'Binary Tree part-III', 'Symmetric Binary Tree', 'Easy', 'https://leetcode.com/problems/symmetric-tree/', 'leetcode', 'symmetric-tree'),
    (128, 'Binary Tree part-III', 'Flatten Binary Tree to LinkedList', 'Medium', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', 'leetcode', 'flatten-binary-tree-to-linked-list'),
    (129, 'Binary Tree part-III', 'Check if Binary Tree is the mirror of itself or not', 'Easy', 'https://practice.geeksforgeeks.org/problems/mirror-tree/1', 'geeksforgeeks', null),
    (130, 'Binary Tree part-III', 'Check for Children Sum Property', 'Medium', 'https://practice.geeksforgeeks.org/problems/children-sum-parent/1', 'geeksforgeeks', null),
    (131, 'Binary Search Tree', 'Populate Next Right pointers of Tree', 'Medium', 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', 'leetcode', 'populating-next-right-pointers-in-each-node'),
    (132, 'Binary Search Tree', 'Search given Key in BST', 'Easy', 'https://leetcode.com/problems/search-in-a-binary-search-tree/', 'leetcode', 'search-in-a-binary-search-tree'),
    (133, 'Binary Search Tree', 'Construct BST from given keys', 'Medium', 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', 'leetcode', 'convert-sorted-array-to-binary-search-tree'),
    (134, 'Binary Search Tree', 'Construct BST from preorder traversal', 'Medium', 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/', 'leetcode', 'construct-binary-search-tree-from-preorder-traversal'),
    (135, 'Binary Search Tree', 'Check is a BT is BST or not', 'Medium', 'https://leetcode.com/problems/validate-binary-search-tree/', 'leetcode', 'validate-binary-search-tree'),
    (136, 'Binary Search Tree', 'Find LCA of two nodes in BST', 'Medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 'leetcode', 'lowest-common-ancestor-of-a-binary-search-tree'),
    (137, 'Binary Search Tree', 'Find the inorder predecessor/successor of a given Key in BST', 'Medium', 'https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1', 'geeksforgeeks', null),
    (138, 'Binary Search Tree Part-II', 'Floor in a BST', 'Medium', 'https://practice.geeksforgeeks.org/problems/floor-in-bst/1', 'geeksforgeeks', null),
    (139, 'Binary Search Tree Part-II', 'Ceil in a BST', 'Medium', 'https://practice.geeksforgeeks.org/problems/implementing-ceil-in-bst/1', 'geeksforgeeks', null),
    (140, 'Binary Search Tree Part-II', 'Find K-th smallest element in BST', 'Medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 'leetcode', 'kth-smallest-element-in-a-bst'),
    (141, 'Binary Search Tree Part-II', 'Find K-th largest element in BST', 'Easy', 'https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1', 'geeksforgeeks', null),
    (142, 'Binary Search Tree Part-II', 'Find a pair with a given sum in BST', 'Easy', 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/', 'leetcode', 'two-sum-iv-input-is-a-bst'),
    (143, 'Binary Search Tree Part-II', 'BST iterator', 'Medium', 'https://leetcode.com/problems/binary-search-tree-iterator/', 'leetcode', 'binary-search-tree-iterator'),
    (144, 'Binary Search Tree Part-II', 'Size of largest BST in a Binary Tree', 'Medium', 'https://practice.geeksforgeeks.org/problems/largest-bst/1', 'geeksforgeeks', null),
    (145, 'Binary Search Tree Part-II', 'Serialize and deserialize Binary Tree', 'Hard', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 'leetcode', 'serialize-and-deserialize-binary-tree'),
    (146, 'Binary Trees[Miscellaneous]', 'Binary Tree to Double Linked List', 'Medium', 'https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/1', 'geeksforgeeks', null),
    (147, 'Binary Trees[Miscellaneous]', 'Find median in a stream of running integers', 'Hard', 'https://leetcode.com/problems/find-median-from-data-stream/', 'leetcode', 'find-median-from-data-stream'),
    (148, 'Binary Trees[Miscellaneous]', 'K-th largest element in a stream', 'Easy', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 'leetcode', 'kth-largest-element-in-a-stream'),
    (149, 'Binary Trees[Miscellaneous]', 'Distinct numbers in Window', 'Medium', 'https://www.interviewbit.com/problems/distinct-numbers-in-window/', 'interviewbit', null),
    (150, 'Binary Trees[Miscellaneous]', 'K-th largest element in an unsorted array', 'Medium', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 'leetcode', 'kth-largest-element-in-an-array'),
    (151, 'Binary Trees[Miscellaneous]', 'Flood-fill Algorithm', 'Easy', 'https://leetcode.com/problems/flood-fill/', 'leetcode', 'flood-fill'),
    (152, 'Graph', 'Clone Graph', 'Medium', 'https://leetcode.com/problems/clone-graph/', 'leetcode', 'clone-graph'),
    (153, 'Graph', 'DFS of Graph', 'Easy', 'https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1', 'geeksforgeeks', null),
    (154, 'Graph', 'BFS of Graph', 'Easy', 'https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1', 'geeksforgeeks', null),
    (155, 'Graph', 'Detect A cycle in Undirected Graph using BFS', 'Medium', 'https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1', 'geeksforgeeks', null),
    (156, 'Graph', 'Detect A cycle in Undirected Graph using DFS', 'Medium', 'https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1', 'geeksforgeeks', null),
    (157, 'Graph', 'Detect A cycle in a Directed Graph using DFS', 'Medium', 'https://leetcode.com/problems/course-schedule/', 'leetcode', 'course-schedule'),
    (158, 'Graph', 'Detect A cycle in a Directed Graph using BFS', 'Medium', 'https://leetcode.com/problems/course-schedule/', 'leetcode', 'course-schedule'),
    (159, 'Graph', 'Topological Sort', 'Medium', 'https://practice.geeksforgeeks.org/problems/topological-sort/1', 'geeksforgeeks', null),
    (160, 'Graph', 'Number of Islands', 'Medium', 'https://leetcode.com/problems/number-of-islands/', 'leetcode', 'number-of-islands'),
    (161, 'Graph', 'Bipartite Check using BFS', 'Medium', 'https://leetcode.com/problems/is-graph-bipartite/', 'leetcode', 'is-graph-bipartite'),
    (162, 'Graph', 'Bipartite Check using DFS', 'Medium', 'https://leetcode.com/problems/is-graph-bipartite/', 'leetcode', 'is-graph-bipartite'),
    (163, 'Graph Part-II', 'Strongly Connected Component (Kosaraju''s Algo)', 'Hard', 'https://practice.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1', 'geeksforgeeks', null),
    (164, 'Graph Part-II', 'Dijkstra''s Algorithm', 'Medium', 'https://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1', 'geeksforgeeks', null),
    (165, 'Graph Part-II', 'Bellman-Ford Algorithm', 'Medium', 'https://practice.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/0', 'geeksforgeeks', null),
    (166, 'Graph Part-II', 'Floyd Warshall Algorithm', 'Medium', 'https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1', 'geeksforgeeks', null),
    (167, 'Graph Part-II', 'MST using Prim''s Algo', 'Medium', 'https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1', 'geeksforgeeks', null),
    (168, 'Graph Part-II', 'MST using Kruskal''s Algo', 'Medium', 'https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1', 'geeksforgeeks', null),
    (169, 'Dynamic Programming', 'Maximum Product Subarray', 'Medium', 'https://leetcode.com/problems/maximum-product-subarray/', 'leetcode', 'maximum-product-subarray'),
    (170, 'Dynamic Programming', 'Longest Increasing Subsequence', 'Medium', 'https://leetcode.com/problems/longest-increasing-subsequence/', 'leetcode', 'longest-increasing-subsequence'),
    (171, 'Dynamic Programming', 'Longest Common Subsequence', 'Medium', 'https://leetcode.com/problems/longest-common-subsequence/', 'leetcode', 'longest-common-subsequence'),
    (172, 'Dynamic Programming', '0-1 Knapsack', 'Medium', 'https://practice.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1', 'geeksforgeeks', null),
    (173, 'Dynamic Programming', 'Edit Distance', 'Hard', 'https://leetcode.com/problems/edit-distance/', 'leetcode', 'edit-distance'),
    (174, 'Dynamic Programming', 'Maximum sum increasing subsequence', 'Medium', 'https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1', 'geeksforgeeks', null),
    (175, 'Dynamic Programming', 'Matrix Chain Multiplication', 'Hard', 'https://practice.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1', 'geeksforgeeks', null),
    (176, 'Dynamic Programming Part-II', 'Minimum Path Sum In a Grid', 'Medium', 'https://leetcode.com/problems/minimum-path-sum/', 'leetcode', 'minimum-path-sum'),
    (177, 'Dynamic Programming Part-II', 'Coin Change', 'Medium', 'https://leetcode.com/problems/coin-change/', 'leetcode', 'coin-change'),
    (178, 'Dynamic Programming Part-II', 'Subset Sum', 'Medium', 'https://practice.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1', 'geeksforgeeks', null),
    (179, 'Dynamic Programming Part-II', 'Rod Cutting', 'Medium', 'https://practice.geeksforgeeks.org/problems/rod-cutting0840/1', 'geeksforgeeks', null),
    (180, 'Dynamic Programming Part-II', 'Egg Dropping', 'Hard', 'https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle-1587115620/1', 'geeksforgeeks', null),
    (181, 'Dynamic Programming Part-II', 'Word Break', 'Medium', 'https://leetcode.com/problems/word-break/', 'leetcode', 'word-break'),
    (182, 'Dynamic Programming Part-II', 'Palindrome Partitioning (MCM Variation)', 'Hard', 'https://practice.geeksforgeeks.org/problems/palindromic-patitioning4845/1', 'geeksforgeeks', null),
    (183, 'Dynamic Programming Part-II', 'Maximum Profit in Job Scheduling', 'Hard', 'https://leetcode.com/problems/maximum-profit-in-job-scheduling/', 'leetcode', 'maximum-profit-in-job-scheduling'),
    (184, 'Trie', 'Implement Trie (Prefix Tree)', 'Medium', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 'leetcode', 'implement-trie-prefix-tree'),
    (185, 'Trie', 'Implement Trie II', 'Medium', 'https://www.codingninjas.com/studio/problems/implement-trie_1387095', 'codingninjas', null),
    (186, 'Trie', 'Longest String with All Prefixes', 'Medium', 'https://www.codingninjas.com/studio/problems/complete-string_2687860', 'codingninjas', null),
    (187, 'Trie', 'Number of Distinct Substrings in a String', 'Medium', 'https://www.codingninjas.com/studio/problems/count-distinct-substrings_985292', 'codingninjas', null),
    (188, 'Trie', 'Power Set', 'Medium', 'https://practice.geeksforgeeks.org/problems/power-set4302/1', 'geeksforgeeks', null),
    (189, 'Trie', 'Maximum XOR of Two Numbers in an Array', 'Medium', 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', 'leetcode', 'maximum-xor-of-two-numbers-in-an-array'),
    (190, 'Trie', 'Maximum XOR With an Element From Array', 'Hard', 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/', 'leetcode', 'maximum-xor-with-an-element-from-array')
  ) as v(sort_order, section, title, difficulty, url, source, external_ref)
  where not exists (
    select 1 from challenge_items ci
    where ci.challenge_id = chal_id and ci.sort_order = v.sort_order
  );
end $$;
